{"uuid": "fcd5d11b-22e3-48b9-8e46-dec7083aab3d", "children": ["9f5900bc-08a3-494d-a12f-554896128cdf", "0fa50362-76c9-49b3-ac47-96329b9d0224", "52fc9a96-eda8-4c5e-90eb-6f3b2d7fe47a", "28e8e997-feb9-4155-940a-ed8f2f30643f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=100.0.4896.60)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00C58BD3+2395091]\n\tOrdinal0 [0x00BEACA1+1944737]\n\tOrdinal0 [0x00ADD008+839688]\n\tOrdinal0 [0x00ACF21E+782878]\n\tOrdinal0 [0x00ACEE0F+781839]\n\tOrdinal0 [0x00ACE426+779302]\n\tOrdinal0 [0x00ACD335+774965]\n\tOrdinal0 [0x00ACD938+776504]\n\tOrdinal0 [0x00AD95D0+824784]\n\tOrdinal0 [0x00ACEC1D+781341]\n\tOrdinal0 [0x00ACF7F8+784376]\n\tOrdinal0 [0x00ACEE2A+781866]\n\tOrdinal0 [0x00ACE426+779302]\n\tOrdinal0 [0x00ACD335+774965]\n\tOrdinal0 [0x00ACD80D+776205]\n\tOrdinal0 [0x00ADE80A+845834]\n\tOrdinal0 [0x00B3541D+1201181]\n\tOrdinal0 [0x00B24BBC+1133500]\n\tOrdinal0 [0x00B34D62+1199458]\n\tOrdinal0 [0x00B249D6+1133014]\n\tOrdinal0 [0x00AFEF76+978806]\n\tOrdinal0 [0x00AFFE86+982662]\n\tGetHandleVerifier [0x00E0C912+1719138]\n\tGetHandleVerifier [0x00EBB2CD+2434333]\n\tGetHandleVerifier [0x00CF4001+569937]\n\tGetHandleVerifier [0x00CF3066+565942]\n\tOrdinal0 [0x00BF265B+1975899]\n\tOrdinal0 [0x00BF72A8+1995432]\n\tOrdinal0 [0x00BF7395+1995669]\n\tOrdinal0 [0x00C002F1+2032369]\n\tBaseThreadInitThunk [0x761D6739+25]\n\tRtlGetFullPathName_UEx [0x77758FEF+1215]\n\tRtlGetFullPathName_UEx [0x77758FBD+1165]\n\n", "trace": "  File \"D:\\Python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JBen\\JBen.python\\color\\test_case\\test_case1.py\", line 15, in driver\n    lp.login('admin', '123456')\n  File \"D:\\JBen\\JBen.python\\color\\page_object\\login_page.py\", line 15, in login\n    self.geturl(self.url)\n  File \"D:\\JBen\\JBen.python\\color\\base\\base_page.py\", line 16, in geturl\n    self.driver.get(url)\n  File \"D:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1656651976870, "stop": 1656651978252}], "start": 1656651976870, "stop": 1656651978368}